export const dataMen = [
    /********** Bermudas **********/
    {
        id: "1",
        name: "Bermuda Azul",
        price: 15000,
        category: "shorts",
        image: "../api-products/images/men/shorts/Bermuda-Azul-Stock.jpg",
        variant: "../api-products/images/men/shorts/variants/Bermuda-Azul.jpg",
    },
    {
        id: "2",
        name: "Bermuda Blanca",
        price: 15000,
        category: "shorts",
        image: "../api-products/images/men/shorts/Bermuda-Blanca-Stock.jpg",
        variant: "../api-products/images/men/shorts/variants/Bermuda-Blanca.jpg",
    },
    /********** Pantalones **********/
    {
        id: "3",
        name: "Pantalon Beige",
        price: 15000,
        category: "pants",
        image: "../api-products/images/men/pants/Pantalon-beige-Stock.jpg",
        variant: "../api-products/images/men/pants/variants/Pantalon-beige-BLC.jpg",
    },
    {
        id: "4",
        name: "Pantalon Blanco",
        price: 15000,
        category: "pants",
        image: "../api-products/images/men/pants/Pantalon-blanco-Stock.jpg",
        variant: "../api-products/images/men/pants/variants/Pantalon-blanco-BLC.jpg",
    },
    {
        id: "5",
        name: "Pantalon Gris",
        price: 15000,
        category: "pants",
        image: "../api-products/images/men/pants/Pantalon-gris-Stock.jpg",
        variant: "../api-products/images/men/pants/variants/Pantalon-gris-BLC.jpg",
    },
    /********** Camisas **********/
    {
        id: "6",
        name: "Camisa Azul",
        price: 15000,
        category: "shirts",
        image: "../api-products/images/men/shirts/Camisa-azul-Stock.jpg",
        variant: "../api-products/images/men/shirts/variants/Camisa-azul-Blc.jpg",
    },
    {
        id: "7",
        name: "Camisa Blanca",
        price: 15000,
        category: "shirts",
        image: "../api-products/images/men/shirts/Camisa-blanca-Stock.jpg",
        variant: "../api-products/images/men/shirts/variants/Camisa-blanca-Blc.jpg",
    },
    {
        id: "8",
        name: "Camisa Gris",
        price: 15000,
        category: "shirts",
        image: "../api-products/images/men/shirts/Camisa-gris-Stock.jpg",
        variant: "../api-products/images/men/shirts/variants/Camisa-gris-Blc.jpg",
    },
    {
        id: "9",
        name: "Camisa Rosa",
        price: 15000,
        category: "shirts",
        image: "../api-products/images/men/shirts/Camisa-rosa-Stock.jpg",
        variant: "../api-products/images/men/shirts/variants/Camisa-rosa-Blc.jpg",
    },
    /********** Remeras **********/
    {
        id: "10",
        name: "Polo Azul",
        price: 15000,
        category: "t-shirts",
        image: "../api-products/images/men/t-shirts/Polo-azul-Stock.jpg",
        variant: "../api-products/images/men/t-shirts/variants/Polo-azul.jpg",
    },
    {
        id: "11",
        name: "Polo Rayado",
        price: 15000,
        category: "t-shirts",
        image: "../api-products/images/men/t-shirts/Polo-Rayas-Stock.jpg",
        variant: "../api-products/images/men/t-shirts/variants/Polo-Rayas.jpg",
    },
    {
        id: "12",
        name: "Remera Amarilla",
        price: 15000,
        category: "t-shirts",
        image: "../api-products/images/men/t-shirts/Remera-amarilla-Stock.jpg",
        variant: "../api-products/images/men/t-shirts/variants/Remera-amarilla.jpg",
    },
]