export const dataWomen = [
  // ****************** Shorts ******************
  {
    id: "1",
    name: "Short Rosa",
    price: 15000,
    category: "short",
    image: "../api-products/images/women/shorts/Bermuda-rosa-stock.jpg",
    variant: "../api-products/images/women/shorts/variants/Bermuda-rosa.jpg",
  },
  {
    id: "2",
    name: "Short Marron",
    price: 15000,
    category: "short",
    image: "../api-products/images/women/shorts/Bermuda-marron-stock.jpg",
    variant: "../api-products/images/women/shorts/variants/Bermuda-marron.jpg",
  },
  {
    id: "3",
    name: "Short Negro",
    price: 15000,
    category: "short",
    image: "../api-products/images/women/shorts/Bermuda-negro-stock.jpg",
    variant: "../api-products/images/women/shorts/variants/Bermuda-negro.jpg",
  },
  // ****************** Pants ******************

  {
    id: "4",
    name: "Pantalon Celeste",
    price: 15000,
    category: "pants",
    image: "../api-products/images/women/pants/Pantalon-celeste-stock.jpg",
    variant: "../api-products/images/women/pants/variants/Pantalon-celeste.jpg",
  },
  {
    id: "5",
    name: "Pantalon Gris",
    price: 15000,
    category: "pants",
    image: "../api-products/images/women/pants/Pantalon-gris-stock.jpg",
    variant: "../api-products/images/women/pants/variants/Pantalon-gris.jpg",
  },
  {
    id: "6",
    name: "Pantalon Negro",
    price: 15000,
    category: "pants",
    image: "../api-products/images/women/pants/Pantalon-negro-stock.jpg",
    variant: "../api-products/images/women/pants/variants/Pantalon-negro.jpg",
  },
  {
    id: "7",
    name: "Pantalon Violeta",
    price: 15000,
    category: "pants",
    image: "../api-products/images/women/pants/Pantalon-violeta-stock.jpg",
    variant: "../api-products/images/women/pants/variants/pantalon-violeta.jpg",
  },
  {
    id: "8",
    name: "Pantalon Beige",
    price: 15000,
    category: "pants",
    image: "../api-products/images/women/pants/Pantalon-beige-stock.jpg",
    variant: "../api-products/images/women/pants/variants/Pantalon-beige.jpg",
  },
  // ****************** Skirts ******************
  {
    id: "9",
    name: "Falda Beige",
    price: 15000,
    category: "skirts",
    image: "../api-products/images/women/skirts/Falda-beige-stock.jpg",
    variant: "../api-products/images/women/skirts/variants/Falda-beige.jpg",
  },
  {
    id: "10",
    name: "Falda Celeste",
    price: 15000,
    category: "skirts",
    image: "../api-products/images/women/skirts/Falda-celeste-stock.jpg",
    variant: "../api-products/images/women/skirts/variants/Falda-celeste.jpg",
  },
  {
    id: "11",
    name: "Falda Marron",
    price: 15000,
    category: "skirts",
    image: "../api-products/images/women/skirts/Falda-marron-stock.jpg",
    variant: "../api-products/images/women/skirts/variants/Falda-marron.jpg",
  },
  {
    id: "12",
    name: "Falda Negra",
    price: 15000,
    category: "skirts",
    image: "../api-products/images/women/skirts/Falda-negra-stock.jpg",
    variant: "../api-products/images/women/skirts/variants/Falda-negra.jpg",
  },
  {
    id: "13",
    name: "Falda Verde",
    price: 15000,
    category: "skirts",
    image: "../api-products/images/women/skirts/Falda-verde-stock.jpg",
    variant: "../api-products/images/women/skirts/variants/Falda-verde.jpg",
  },
  // ****************** T-shirts ******************
  {
    id: "14",
    name: "Remera Azul",
    price: 15000,
    category: "t-shirt",
    image: "../api-products/images/women/t-shirts/Remera-azul-stock.jpg",
    variant: "../api-products/images/women/t-shirts/variants/Remera-azul.jpg",
  },
  {
    id: "15",
    name: "Remera Beige",
    price: 15000,
    category: "t-shirt",
    image: "../api-products/images/women/t-shirts/Remera-beige-stock.jpg",
    variant: "../api-products/images/women/t-shirts/variants/Remera-beige.jpg",
  },
  {
    id: "16",
    name: "Remera Blanca",
    price: 15000,
    category: "t-shirt",
    image: "../api-products/images/women/t-shirts/Remera-blanca-stock.jpg",
    variant: "../api-products/images/women/t-shirts/variants/Remera-blanca.jpg",
  },
  {
    id: "17",
    name: "Remera dorado",
    price: 15000,
    category: "t-shirt",
    image: "../api-products/images/women/t-shirts/Remera-dorado-stock.jpg",
    variant: "../api-products/images/women/t-shirts/variants/Remera-dorado.jpg",
  },
  {
    id: "18",
    name: "Remera Marron",
    price: 15000,
    category: "t-shirt",
    image: "../api-products/images/women/t-shirts/Remera-marron-stock.jpg",
    variant: "../api-products/images/women/t-shirts/variants/Remera-marron.jpg",
  },
  {
    id: "19",
    name: "Remera Negra",
    price: 15000,
    category: "t-shirt",
    image: "../api-products/images/women/t-shirts/Remera-negra-stock.jpg",
    variant: "../api-products/images/women/t-shirts/variants/Remera-negra.jpg",
  },
  {
    id: "20",
    name: "Remera Verde",
    price: 15000,
    category: "t-shirt",
    image: "../api-products/images/women/t-shirts/Remera-verde-stock.jpg",
    variant: "../api-products/images/women/t-shirts/variants/Remera-verde.jpg",
  }
];
